language: python
python:
  - 2.7

before_script:
  - echo $SSH_PUSH_KEY | tr " " "\n" > ~/.ssh/id_rsa
  - cat ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - cat ~/.ssh/config
  - ssh -vvvv git@github.com
  - echo $TRAVIS_TAG
  - echo $TRAVIS_BRANCH
  - echo $TRAVIS_COMMIT
  - git status
  - git config --global push.default simple
  - git config --global user.email "datasets-update-bot@lexman.org"
  - git config --global user.name "Update bot"

install:
  - pip install --upgrade -r scripts/requirements.txt

script:
  - cat .git/config
  - cd scripts
  - make valid.txt
  - git status

after_success:
  - git status
  - DATE=`date`
  - echo "test,test,$DATE" >> ../data/sp500-companies.csv
  - git status
  - git checkout -B $TRAVIS_BRANCH
  - git status
  - make pushed.txt
  - git status
  