language: python
python:
  - 2.7

before_script:
  - echo "-----BEGIN RSA PRIVATE KEY-----" >> ~/.ssh/id_rsa
  - echo "$SSH_PUSH_KEY" | sed 's/ /\n/g' >> ~/.ssh/id_rsa
  - echo "-----END RSA PRIVATE KEY-----" >> ~/.ssh/id_rsa
  - cat ~/.ssh/id_rsa
  - diff ex-continuous-processing ~/.ssh/id_rsa || echo "toto"
  - cp ex-continuous-processing ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - cat ~/.ssh/config
  - ssh -vvvv git@github.com || echo "Ssh has been tested"
  - echo $TRAVIS_TAG
  - echo $TRAVIS_BRANCH
  - echo $TRAVIS_COMMIT
  - git status
  - git config --global push.default simple
  - git config --global user.email "datasets-update-bot@lexman.org"
  - git config --global user.name "Update bot"
  - git remote add publish git@github.com:lexman/ex-continuous-processing.git

install:
  - pip install --upgrade -r scripts/requirements.txt

script:
  - cat .git/config
  - cd scripts
  - make valid.txt
  - git status
  - DATE=`date`
  - echo "test,test,$DATE" >> ../data/sp500-companies.csv
  - git status
  
deploy:
  skip_cleanup: true
  provider: script
  script: git checkout -B $TRAVIS_BRANCH && make pushed.txt