language: python
python:
  - 2.7
  
before_script:
  - echo $SSH_PUSH_KEY > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - cat ~/.ssh/config

install:
  - pip install --upgrade -r scripts/requirements.txt

script:
  - .git/config
  - cd scripts
  - make
